name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
        run: |
          docker login -u $DOCKER_HUB -p $DOCKER_SECRET
          docker build -t alinz/baker:latest .
          docker push alinz/baker:latest
