name: CI
on:
  push:
    branches:
      - master
    paths:
      - '**/*.yml'
      - '**/*.go'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
    paths-ignore:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
          GITHUB_DOCKER_SECRET: ${{ secrets.GITHUB_DOCKER_SECRET }}
        run: |
          # deploy to docker hub
          docker build -t alinz/baker:latest .
          echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
          docker push alinz/baker:latest

          # deploy to github package
          docker build -t docker.pkg.github.com/alinz/baker/baker:latest .
          echo ${{ secrets.GITHUB_DOCKER_SECRET }}docker login docker.pkg.github.com --username alinz --password-stdin
          docker push docker.pkg.github.com/alinz/baker/baker:latest
